'use strict';
const assert = require('assert'), fs = require('fs'), path = require('path');
const P = path.resolve(__dirname, '../public/');
const html = fs.readFileSync(P + '/index.html', 'utf8');
const fb = fs.readFileSync(P + '/feedback.js', 'utf8');
let n = 0; const ok = (m, c) => { assert.ok(c, m); n++; };
const ids = new Set([...html.matchAll(/id="([^"]+)"/g)].map(m => m[1]));
ok('feedback lives in AI panel (fb-send)', ids.has('fb-send') && ids.has('fb-text') && ids.has('fb-donate'));
ok('AI badge for unread', ids.has('ai-badge'));
ok('tabs chat/feedback/settings/logs', ['tab-chat','tab-feedback','tab-settings','tab-logs'].every(i => ids.has(i)));
ok('shfh client file present or load path', fs.existsSync(path.join(P, 'shfh-client.js')) || /shfh-client/.test(fb));
ok('feedback.js marks read + badge', /__fbMarkRead/.test(fb) && /ai-badge/.test(fb));
ok('donate not hard-coded accounts', !/0123456789|GABC123/.test(fb));
ok('hub credentials only via /api/shfh-config', /\/api\/shfh-config/.test(fb));
console.log('feedback-hub: ' + n + '/' + n + ' passed (panel-integrated)');
